TASK0:
  name: MM
  type: VL-logit
  num_labels: 1
  loss: CrossEntropyLoss
  process: retrieval
  task_id: 0
  dataroot: /project/dmg_data/MMdata
  features_h5path1: /project/dmg_data/MMdata/imgfeats/volta/coco-vist_feat.lmdb
  features_h5path2: ''
  train_annotations_jsonpath: ''
  val_annotations_jsonpath: /project/dmg_data/MMdata/coco-vist_ann.jsonl
  max_seq_length: 512
  max_region_num: 36
  batch_size: 64
  train_split: ''
  val_split: test
TASK1:
  name: VQA
  type: VL-classifier
  num_labels: 3129
  loss: BCEWithLogitLoss
  process: normal
  task_id: 1
  dataroot: datasets/vqa/annotations
  features_h5path1: datasets/mscoco/resnet101_faster_rcnn_genome_imgfeats/volta/test_feat.lmdb
  features_h5path2: ''
  train_annotations_jsonpath: ''
  val_annotations_jsonpath: ''
  max_seq_length: 38
  max_region_num: 36
  batch_size: 128
  eval_batch_size: 1024
  train_split: ''
  val_split: test
TASK8:
  name: RetrievalFlickr30k
  type: VL-logit
  num_labels: 1
  loss: CrossEntropyLoss
  process: retrieval
  task_id: 8
  dataroot: /project/dmg_data/MMdata 
  # /project/dmg_data/data-volta/flickr30k
  # datasets/flickr30k
  features_h5path1: /project/dmg_data/MMdata/imgfeats/volta/coco-vist_feat.lmdb 
  # /project/dmg_data/data-volta/flickr30k/resnet101_faster_rcnn_genome_imgfeats/volta/flickr30k_feat.lmdb 
  # datasets/flickr30k/resnet101_faster_rcnn_genome_imgfeats/volta/flickr30k_feat.lmdb
  features_h5path2: ''
  train_annotations_jsonpath: ''
  val_annotations_jsonpath: /project/dmg_data/MMdata/coco-vist_ann1000.jsonl 
  # /project/dmg_data/data-volta/flickr30k/annotations/test_ann.jsonl
  # datasets/flickr30k/annotations/test_ann.jsonl
  max_seq_length: 512 # was 38
  # here I can have max_seq of VIST
  max_region_num: 36
  batch_size: 64
  train_split: ''
  val_split: test
TASK10:
  name: refcoco+
  type: V-logit
  loss: BCEWithLogitLoss
  process: normal
  task_id: 10
  dataroot: datasets/refcoco+_unc/annotations
  features_h5path1: datasets/refcoco+_unc/resnet101_faster_rcnn_genome_imgfeats/volta/refcoco+_unc_dets36_feat.lmdb
  features_h5path2: ''
  train_annotations_jsonpath: ''
  val_annotations_jsonpath: ''
  max_seq_length: 38
  max_region_num: 36
  batch_size: 256
  eval_batch_size: 1024
  train_split: ''
  val_split: test
TASK12:
  name: NLVR2
  type: VL-binary-classifier
  num_labels: 2
  loss: BCEWithLogitLoss
  process: nlvr
  task_id: 12
  dataroot: datasets/nlvr2/annotations
  features_h5path1: datasets/nlvr2/resnet101_faster_rcnn_genome_imgfeats/volta/nlvr2_feat.lmdb
  features_h5path2: ''
  train_annotations_jsonpath: ''
  val_annotations_jsonpath: ''
  max_seq_length: 38
  max_region_num: 36
  batch_size: 64
  eval_batch_size: 512
  train_split: ''
  val_split: test
